### ISSUE TITLE
running example

### ISSUE THREAD

**Issue by phiripatrick663** [amient/hello-kafka-streams#2]
I followed the instructions to run this example with some limited success. Tow things are not quite clear to me;
   a). the instruction to update gradle.properties in confluent is not clear - how to do it
  b) my attempt to compile example resulted in a failure - missing Kafka-streams/0.10.1.0-SNAPSHOT jar file.

If I use confluent-alpha1 instead of the not yet released Kafka 0.10.1.0, how do I connect the example to the running Kafka instance?

**Comment by michal-harish** [comment]
Hi, thanks for heads up. I actually haven't tried it with the Confluent
install, I worked with kafka trunk.  Did you manage to run it ? I will
download the preview release and update the README.md when I have a moment.

**Comment by michal-harish** [comment]
OK, I've just realised that the confluent tech.preview is based on Kafka 0.9.x - I will have to create a branch of the demo itself because the APIs are slightly different..

**Comment by phiripatrick663** [comment]
Thanks.  No I didn't have kafka trunk, will try a clone and see.

**Comment by michal-harish** [comment]
demo backported to the API version bundled with confluent platform tech.preview alpha; under 'cp' branch; tested and updated README.md setup guide

**Comment by phiripatrick663** [comment]
Hi Michal,

Thanks for the updates to github, instructions are clearer. There is still
one issue on the Confluent side, the
connect-api.jar/connect-api-0.10.1.0-SNAPSHOT.jar is missing. The one
logical place ; share/java/kafka does not have it.

I will redouble my efforts on the Confluent site and see if there was any
compilation necessary, I doubt it though.  In that case it leaves obtaining
a Kafka trunk folder as the one sure way to test app.

Thanks.
Patrick.

**Comment by michal-harish** [comment]
It should be looking for connect-api-0.9.1.0-cp1.jar, if you are on the cp branch the build.gradle contains ext.kafkaVersion='0.9.1.0-cp1'

and there is a dependency

compile group: 'org.apache.kafka', name: 'connect-api', version: kafkaVersion

**Comment by phiripatrick663** [comment]
Ok, I saw that in the java folder. What needs to change in build.gradle to
look for connect-api-0.9.1.0-cp1.jar?

Thanks.

**Comment by michal-harish** [comment]
What I mean is: I have already changed it and it works correctly for me.
Are you sure you have uptodate cp branch with no local modifications?

./gradlew clean build

**Comment by phiripatrick663** [comment]
I believe I do, just downloaded it yesterday and have not made any
modifications. Here is error message;

hduser@hduser-VirtualBox:/usr/local/hello-kafka-streams$ ./gradlew clean
build

FAILURE: Build failed with an exception.
- Where:
  Build file '/usr/local/hello-kafka-streams/build.gradle' line: 44
- What went wrong:
  Could not resolve all dependencies for configuration ':compile'.
  
  > Could not find org.apache.kafka:connect-runtime:0.10.1.0-SNAPSHOT.
  > Searched in the following locations:

file:/home/hduser/.m2/repository/org/apache/kafka/connect-runtime/0.10.1.0-SNAPSHOT/maven-metadata.xml

file:/home/hduser/.m2/repository/org/apache/kafka/connect-runtime/0.10.1.0-SNAPSHOT/connect-runtime-0.10.1.0-SNAPSHOT.pom

file:/home/hduser/.m2/repository/org/apache/kafka/connect-runtime/0.10.1.0-SNAPSHOT/connect-runtime-0.10.1.0-SNAPSHOT.jar

https://repo1.maven.org/maven2/org/apache/kafka/connect-runtime/0.10.1.0-SNAPSHOT/maven-metadata.xml

https://repo1.maven.org/maven2/org/apache/kafka/connect-runtime/0.10.1.0-SNAPSHOT/connect-runtime-0.10.1.0-SNAPSHOT.pom

https://repo1.maven.org/maven2/org/apache/kafka/connect-runtime/0.10.1.0-SNAPSHOT/connect-runtime-0.10.1.0-SNAPSHOT.jar

file:/usr/local/confluent-2.1.0-alpha1/share/java/kafka/connect-runtime-0.10.1.0-SNAPSHOT.jar

file:/usr/local/confluent-2.1.0-alpha1/share/java/kafka/connect-runtime.jar
  Required by:
      :hello-kafka-streams:0.10.1.0-SNAPSHOT

> Could not find org.apache.kafka:connect-api:0.10.1.0-SNAPSHOT.
>   Searched in the following locations:

file:/home/hduser/.m2/repository/org/apache/kafka/connect-api/0.10.1.0-SNAPSHOT/maven-metadata.xml

file:/home/hduser/.m2/repository/org/apache/kafka/connect-api/0.10.1.0-SNAPSHOT/connect-api-0.10.1.0-SNAPSHOT.pom

file:/home/hduser/.m2/repository/org/apache/kafka/connect-api/0.10.1.0-SNAPSHOT/connect-api-0.10.1.0-SNAPSHOT.jar

https://repo1.maven.org/maven2/org/apache/kafka/connect-api/0.10.1.0-SNAPSHOT/maven-metadata.xml

https://repo1.maven.org/maven2/org/apache/kafka/connect-api/0.10.1.0-SNAPSHOT/connect-api-0.10.1.0-SNAPSHOT.pom

https://repo1.maven.org/maven2/org/apache/kafka/connect-api/0.10.1.0-SNAPSHOT/connect-api-0.10.1.0-SNAPSHOT.jar

file:/usr/local/confluent-2.1.0-alpha1/share/java/kafka/connect-api-0.10.1.0-SNAPSHOT.jar

file:/usr/local/confluent-2.1.0-alpha1/share/java/kafka/connect-api.jar
  Required by:
      :hello-kafka-streams:0.10.1.0-SNAPSHOT

> Could not find org.apache.kafka:kafka-streams:0.10.1.0-SNAPSHOT.
>   Searched in the following locations:

file:/home/hduser/.m2/repository/org/apache/kafka/kafka-streams/0.10.1.0-SNAPSHOT/maven-metadata.xml

file:/home/hduser/.m2/repository/org/apache/kafka/kafka-streams/0.10.1.0-SNAPSHOT/kafka-streams-0.10.1.0-SNAPSHOT.pom

file:/home/hduser/.m2/repository/org/apache/kafka/kafka-streams/0.10.1.0-SNAPSHOT/kafka-streams-0.10.1.0-SNAPSHOT.jar

https://repo1.maven.org/maven2/org/apache/kafka/kafka-streams/0.10.1.0-SNAPSHOT/maven-metadata.xml

https://repo1.maven.org/maven2/org/apache/kafka/kafka-streams/0.10.1.0-SNAPSHOT/kafka-streams-0.10.1.0-SNAPSHOT.pom

https://repo1.maven.org/maven2/org/apache/kafka/kafka-streams/0.10.1.0-SNAPSHOT/kafka-streams-0.10.1.0-SNAPSHOT.jar

file:/usr/local/confluent-2.1.0-alpha1/share/java/kafka/kafka-streams-0.10.1.0-SNAPSHOT.jar

file:/usr/local/confluent-2.1.0-alpha1/share/java/kafka/kafka-streams.jar
  Required by:
      :hello-kafka-streams:0.10.1.0-SNAPSHOT
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or
  --debug option to get more log output.

BUILD FAILED

I just cloned app today, after the changes you made so should be working
with added changes. I added directory path to Confluent. Am I missing
something here?

Thanks.

**Comment by michal-harish** [comment]
I have pushed the fix today so you need to pull. Can you pase here how your
gradle build file looks?

**Comment by phiripatrick663** [comment]
Yes, here it is:
apply plugin: 'idea'

apply plugin: 'application'
mainClassName = 'io.amient.examples.wikipedia.WikipediaStreamDemo'
libsDirName = 'lib'

ext.javaVersion = '1.8'
ext.kafkaVersion = '0.10.1.0-SNAPSHOT'
ext.slf4jVersion = '1.7.6'

sourceCompatibility = 1.8
version = ext.kafkaVersion

build.dependsOn startScripts

task wrapper(type: Wrapper) {
    gradleVersion = '2.7'
}

repositories {
    mavenLocal()
    mavenCentral()
    flatDir {
        dirs '/usr/local/confluent-2.1.0-alpha1/share/java/kafka'
    }
}

dependencies {
    compile group: 'org.apache.kafka', name: 'connect-runtime', version:
kafkaVersion
    compile group: 'org.apache.kafka', name: 'connect-api', version:
kafkaVersion
    compile group: 'org.apache.kafka', name: 'kafka-streams', version:
kafkaVersion
    compile group: 'org.schwering', name: 'irclib', version: '1.10'
    compile group: 'org.slf4j', name:'slf4j-api', version: slf4jVersion
    compile group: 'org.slf4j', name:'slf4j-log4j12', version: slf4jVersion
}

jar {
    manifest {
        attributes 'Main-Class': mainClassName
    }
    from {
        configurations.compile.collect { it.isDirectory() ? it :
zipTree(it) }
    }
}

Is this one good or does not match the new fix?

**Comment by michal-harish** [comment]
yeah, your copy is not up-to-date. this is how the file looks in the repo: [cp/build.gradle](https://github.com/amient/hello-kafka-streams/blob/cp/build.gradle)

This should bring you up to date and clean:

git checkout cp && git reset --hard && git pull

Then again ./gradlew build

**Comment by phiripatrick663** [comment]
Ok, will get it now. Is my file path correct for repositories?

Thanks.

**Comment by michal-harish** [comment]
yeah the dirs looks ok but after reset --hard you'll need to change it back to /usr/local

**Comment by phiripatrick663** [comment]
I got new files to work with and am now running into some compilation java
errors:

hduser@hduser-VirtualBox:/usr/local/hello-kafka-streams$ sudo ./gradlew
build
:compileJava
/usr/local/hello-kafka-streams/src/main/java/org/apache/kafka/connect/api/ConnectEmbedded.java:20:
error: package org.apache.kafka.common.utils does not exist
import org.apache.kafka.common.utils.SystemTime;
                                    ^
/usr/local/hello-kafka-streams/src/main/java/org/apache/kafka/connect/api/ConnectEmbedded.java:21:
error: package org.apache.kafka.common.utils does not exist
import org.apache.kafka.common.utils.Time;
                                    ^
/usr/local/hello-kafka-streams/src/main/java/org/apache/kafka/connect/api/ConnectEmbedded.java:22:
error: package org.apache.kafka.common.utils does not exist
import org.apache.kafka.common.utils.Utils;
                                    ^
/usr/local/hello-kafka-streams/src/main/java/io/amient/examples/wikipedia/WikipediaStreamDemo.java:22:
error: package org.apache.kafka.common.serialization does not exist
import org.apache.kafka.common.serialization.*;
^
/usr/local/hello-kafka-streams/src/main/java/io/amient/examples/wikipedia/JsonPOJOSerde.java:21:
error: package org.apache.kafka.common.errors does not exist
import org.apache.kafka.common.errors.SerializationException;
                                     ^
/usr/local/hello-kafka-streams/src/main/java/io/amient/examples/wikipedia/JsonPOJOSerde.java:22:
error: package org.apache.kafka.common.serialization does not exist
import org.apache.kafka.common.serialization.Deserializer;
                                            ^
/usr/local/hello-kafka-streams/src/main/java/io/amient/examples/wikipedia/JsonPOJOSerde.java:23:
error: package org.apache.kafka.common.serialization does not exist
import org.apache.kafka.common.serialization.Serializer;
                                            ^
/usr/local/hello-kafka-streams/src/main/java/io/amient/examples/wikipedia/JsonPOJOSerde.java:36:
error: cannot find symbol
    public Serializer<T> serializer() {
           ^
  symbol:   class Serializer
  location: class JsonPOJOSerde<T>
  where T is a type-variable:
    T extends Object declared in class JsonPOJOSerde
/usr/local/hello-kafka-streams/src/main/java/io/amient/examples/wikipedia/JsonPOJOSerde.java:61:
error: cannot find symbol
    public Deserializer<T> deserializer() {
           ^
  symbol:   class Deserializer
  location: class JsonPOJOSerde<T>
  where T is a type-variable:
    T extends Object declared in class JsonPOJOSerde
/usr/local/hello-kafka-streams/src/main/java/io/amient/kafka/connect/irc/IRCFeedConnector.java:20:
error: package org.apache.kafka.common.config does not exist
import org.apache.kafka.common.config.ConfigDef;
                                     ^
/usr/local/hello-kafka-streams/src/main/java/io/amient/kafka/connect/irc/IRCFeedConnector.java:21:
error: package org.apache.kafka.common.utils does not exist
import org.apache.kafka.common.utils.AppInfoParser;
                                    ^
/usr/local/hello-kafka-streams/src/main/java/io/amient/kafka/connect/irc/IRCFeedConnector.java:89:
error: cannot find symbol
    public ConfigDef config() {
           ^
  symbol:   class ConfigDef
  location: class IRCFeedConnector
/usr/local/hello-kafka-streams/src/main/java/org/apache/kafka/connect/api/ConnectEmbedded.java:61:
error: cannot find symbol
        Time time = new SystemTime();
        ^
  symbol:   class Time
  location: class ConnectEmbedded
/usr/local/hello-kafka-streams/src/main/java/org/apache/kafka/connect/api/ConnectEmbedded.java:61:
error: cannot find symbol
        Time time = new SystemTime();
                        ^
  symbol:   class SystemTime
  location: class ConnectEmbedded
/usr/local/hello-kafka-streams/src/main/java/org/apache/kafka/connect/api/ConnectEmbedded.java:62:
error: cannot find symbol
        Map<String, String> propsMap = Utils.propsToStringMap(workerConfig);
                                       ^
  symbol:   variable Utils
  location: class ConnectEmbedded
/usr/local/hello-kafka-streams/src/main/java/org/apache/kafka/connect/api/ConnectEmbedded.java:66:
error: cannot access Configurable
        offsetBackingStore.configure(propsMap);
                          ^
  class file for org.apache.kafka.common.Configurable not found
/usr/local/hello-kafka-streams/src/main/java/org/apache/kafka/connect/api/ConnectEmbedded.java:91:
error: cannot find symbol
                herder.putConnectorConfig(name,
Utils.propsToStringMap(connectorConfig), true, cb);
                                                ^
  symbol:   variable Utils
  location: class ConnectEmbedded
/usr/local/hello-kafka-streams/src/main/java/io/amient/examples/wikipedia/WikipediaStreamDemo.java:125:
error: cannot find symbol
        final Serializer<JsonNode> jsonSerializer = new JsonSerializer();
              ^
  symbol:   class Serializer
  location: class WikipediaStreamDemo
/usr/local/hello-kafka-streams/src/main/java/io/amient/examples/wikipedia/WikipediaStreamDemo.java:126:
error: cannot find symbol
        final Deserializer<JsonNode> jsonDeserializer = new
JsonDeserializer();
              ^
  symbol:   class Deserializer
  location: class WikipediaStreamDemo
/usr/local/hello-kafka-streams/src/main/java/io/amient/examples/wikipedia/WikipediaStreamDemo.java:127:
error: cannot find symbol
        final Serializer<String> stringSerializer = new StringSerializer();
              ^
  symbol:   class Serializer
  location: class WikipediaStreamDemo
/usr/local/hello-kafka-streams/src/main/java/io/amient/examples/wikipedia/WikipediaStreamDemo.java:127:
error: cannot find symbol
        final Serializer<String> stringSerializer = new StringSerializer();
                                                        ^
  symbol:   class StringSerializer
  location: class WikipediaStreamDemo
/usr/local/hello-kafka-streams/src/main/java/io/amient/examples/wikipedia/WikipediaStreamDemo.java:128:
error: cannot find symbol
        final Deserializer<String> stringDeserializer = new
StringDeserializer();
              ^
  symbol:   class Deserializer
  location: class WikipediaStreamDemo
/usr/local/hello-kafka-streams/src/main/java/io/amient/examples/wikipedia/WikipediaStreamDemo.java:128:
error: cannot find symbol
        final Deserializer<String> stringDeserializer = new
StringDeserializer();
                                                            ^
  symbol:   class StringDeserializer
  location: class WikipediaStreamDemo
/usr/local/hello-kafka-streams/src/main/java/io/amient/examples/wikipedia/WikipediaStreamDemo.java:129:
error: cannot find symbol
        final Serializer<Long> longSerializer = new LongSerializer();
              ^
  symbol:   class Serializer
  location: class WikipediaStreamDemo
/usr/local/hello-kafka-streams/src/main/java/io/amient/examples/wikipedia/WikipediaStreamDemo.java:129:
error: cannot find symbol
        final Serializer<Long> longSerializer = new LongSerializer();
                                                    ^
  symbol:   class LongSerializer
  location: class WikipediaStreamDemo
/usr/local/hello-kafka-streams/src/main/java/io/amient/examples/wikipedia/WikipediaStreamDemo.java:130:
error: cannot find symbol
        final Deserializer<Long> longDeserializer = new LongDeserializer();
              ^
  symbol:   class Deserializer
  location: class WikipediaStreamDemo
/usr/local/hello-kafka-streams/src/main/java/io/amient/examples/wikipedia/WikipediaStreamDemo.java:130:
error: cannot find symbol
        final Deserializer<Long> longDeserializer = new LongDeserializer();
                                                        ^
  symbol:   class LongDeserializer
  location: class WikipediaStreamDemo
/usr/local/hello-kafka-streams/src/main/java/io/amient/examples/wikipedia/WikipediaStreamDemo.java:132:
error: cannot find symbol
        Deserializer<WikipediaMessage> wikiDeserializer = new
JsonPOJOSerde<>(WikipediaMessage.class).deserializer();
        ^
  symbol:   class Deserializer
  location: class WikipediaStreamDemo
/usr/local/hello-kafka-streams/src/main/java/io/amient/examples/wikipedia/WikipediaStreamDemo.java:133:
error: cannot find symbol
        Serializer<WikipediaMessage> wikiSerializer = new
JsonPOJOSerde<>(WikipediaMessage.class).serializer();
        ^
  symbol:   class Serializer
  location: class WikipediaStreamDemo
/usr/local/hello-kafka-streams/src/main/java/io/amient/examples/wikipedia/JsonPOJOSerde.java:37:
error: cannot find symbol
        return new Serializer<T>() {
                   ^
  symbol:   class Serializer
  location: class JsonPOJOSerde<T>
  where T is a type-variable:
    T extends Object declared in class JsonPOJOSerde
/usr/local/hello-kafka-streams/src/main/java/io/amient/examples/wikipedia/JsonPOJOSerde.java:62:
error: cannot find symbol
        return new Deserializer<T>() {
                   ^
  symbol:   class Deserializer
  location: class JsonPOJOSerde<T>
  where T is a type-variable:
    T extends Object declared in class JsonPOJOSerde
/usr/local/hello-kafka-streams/src/main/java/io/amient/kafka/connect/irc/IRCFeedConnector.java:48:
error: cannot find symbol
        return AppInfoParser.getVersion();
               ^
  symbol:   variable AppInfoParser
  location: class IRCFeedConnector
/usr/local/hello-kafka-streams/src/main/java/io/amient/kafka/connect/irc/IRCFeedConnector.java:94:
error: package ConfigDef does not exist
                .define(TOPIC_CONFIG, ConfigDef.Type.STRING,
ConfigDef.Importance.HIGH, "kafka topic to publish the feed into");
                                               ^
/usr/local/hello-kafka-streams/src/main/java/io/amient/kafka/connect/irc/IRCFeedConnector.java:94:
error: package ConfigDef does not exist
                .define(TOPIC_CONFIG, ConfigDef.Type.STRING,
ConfigDef.Importance.HIGH, "kafka topic to publish the feed into");
                                                                      ^
/usr/local/hello-kafka-streams/src/main/java/io/amient/kafka/connect/irc/IRCFeedConnector.java:93:
error: package ConfigDef does not exist
                .define(IRC_CHANNELS_CONFIG, ConfigDef.Type.STRING,
ConfigDef.Importance.HIGH, "coma-separated list of IRC channels to
subscribe to, e.g. `#en.wikipedia`")
                                                      ^
/usr/local/hello-kafka-streams/src/main/java/io/amient/kafka/connect/irc/IRCFeedConnector.java:93:
error: package ConfigDef does not exist
                .define(IRC_CHANNELS_CONFIG, ConfigDef.Type.STRING,
ConfigDef.Importance.HIGH, "coma-separated list of IRC channels to
subscribe to, e.g. `#en.wikipedia`")

 ^
/usr/local/hello-kafka-streams/src/main/java/io/amient/kafka/connect/irc/IRCFeedConnector.java:92:
error: package ConfigDef does not exist
                .define(IRC_PORT_CONFIG, ConfigDef.Type.INT,
ConfigDef.Importance.HIGH, "IRC server port, e.g. `6667`")
                                                  ^
/usr/local/hello-kafka-streams/src/main/java/io/amient/kafka/connect/irc/IRCFeedConnector.java:92:
error: package ConfigDef does not exist
                .define(IRC_PORT_CONFIG, ConfigDef.Type.INT,
ConfigDef.Importance.HIGH, "IRC server port, e.g. `6667`")
                                                                      ^
/usr/local/hello-kafka-streams/src/main/java/io/amient/kafka/connect/irc/IRCFeedConnector.java:91:
error: package ConfigDef does not exist
                .define(IRC_HOST_CONFIG, ConfigDef.Type.STRING,
ConfigDef.Importance.HIGH, "IRC server host name, e.g `irc.wikimedia.org`")
                                                  ^
/usr/local/hello-kafka-streams/src/main/java/io/amient/kafka/connect/irc/IRCFeedConnector.java:91:
error: package ConfigDef does not exist
                .define(IRC_HOST_CONFIG, ConfigDef.Type.STRING,
ConfigDef.Importance.HIGH, "IRC server host name, e.g `irc.wikimedia.org`")
                                                                         ^
/usr/local/hello-kafka-streams/src/main/java/io/amient/kafka/connect/irc/IRCFeedConnector.java:90:
error: cannot find symbol
        return new ConfigDef()
                   ^
  symbol:   class ConfigDef
  location: class IRCFeedConnector
41 errors
:compileJava FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':compileJava'.
  > Compilation failed; see the compiler error output for details.

I am going through the java files to see if I can spot any differences, so
far the examples/wikipedia files all seem to match updated content.

Thanks.

**Comment by michal-harish** [comment]
The log says that classes are not found > your dependencies are not loading > you haven't updated the dirs path after the resetting your copy. Anyways, closing this issue, the backport to confluent branch is done.

**Comment by phiripatrick663** [comment]
Thanks Michal. You have been a great help.

**Comment by phiripatrick663** [comment]
Hi Michal,

I know you closed this issue but had a couple questions based on the error
I am getting. It looks like the "common" folder is missing from the tree,
this is where all the dependencies should be.
    /usr/local/hello-kafka-streams/src/main/java/org/
apache/kafka/connect/api/

org.apache.kafka.common.????
1.  Is it supposed to be built during the build phase and pull in all the
   dependencies?
2. Should it be part of the  hello-kafka-streams app library already?

Thanks for the help.
Patrick.
