### ISSUE TITLE
follow up to running example

### ISSUE THREAD

**Issue by phiripatrick663** [amient/hello-kafka-streams#4]
Hi Michal,

I know you closed this issue but had a couple questions based on the error
I am getting. It looks like the "common" folder is missing from the tree,
this is where all the dependencies should be.
    /usr/local/hello-kafka-streams/src/main/java/**org/apache/kafka/connect/api**/
                                                                       *\* org.apache.kafka.common**.????
1.  Is it supposed to be built during the build phase and pull in all the
   dependencies?
2. Should it be part of the  hello-kafka-streams app library already?

Thanks for the help.
Patrick.

**Comment by michal-harish** [comment]
Hi, it should automatically be pulled by gradle.

**Comment by phiripatrick663** [comment]
Thanks for the response.  Then there is an issue for me cause its not there
after the build, that's why the compiler is not finding the dependencies.
Any ideas of what I need to do for a fix?

Thanks.

**Comment by michal-harish** [comment]
I am not sure as you report things quite inaccurately - dependencies are
not part of source tree. Read about gradle more.

**Comment by phiripatrick663** [comment]
Sorry mate, had not used gradle before this example. I have done sbt or
maven builds. It would help if you can point me to the part of gradle that
should be downloading the dependencies. Only change done to the build file
was addition of kafka directory.
Thanks

**Comment by michal-harish** [comment]
I see, in that case here is an sbt port of this project: https://github.com/julianpeeters/hello-kafka-streams-twitter
Good luck! :)

**Comment by phiripatrick663** [comment]
Thanks.
